### ISSUE TITLE
systematic way to change the main color theme (pink schema)

### ISSUE THREAD

**Issue by keomd** [smhr/jekyll-theme-smhr-rtl#1]
is there a predefined way to change the main color schema, by that I mean is it possible to change the theme via changing the value of a variable in the config file?

**Comment by smhr** [comment]
I am completely newbie in jekyll, but I think you should change $brand-color in [this file](https://github.com/smhr/jekyll-theme-smhr-rtl/blob/master/assets/css/main.scss).

Please see [jekyll docs](https://jekyllrb.com/docs/themes/) or ask your question [here](https://mehdix.ir/theme-rework.html).
